import os

preContext = '''[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None
PlayResX: 1080
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1
Style: 辉英,Tahoma,35,&H00FFFFFF,&H000000FF,&H003B3C3D,&H00000000,0,0,0,0,70,70,1,0,1,1.3,0.2,2,0,0,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
'''

def readInSrt(path: str) -> list[dict[str, str]]:
    script: list[dict[str, str]] = []
    with open(path, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        for i in range(0, len(lines), 4):
            script.append({
                'id': lines[i].strip(),
                'start': lines[i + 1].split(' --> ')[0].strip().replace(',', '.'),
                'end': lines[i + 1].split(' --> ')[1].strip().replace(',', '.'),
                'content': lines[i + 2].strip()
            })
    return script

def srtToAss(script: list[dict[str, str]]) -> list[dict[str, str]]:
    result: list[dict[str, str]] = []
    for i in range(len(script)):
        result.append({
            "Layer": "0",
            "Start": script[i]['start'],
            "End": script[i]['end'],
            "Style": "辉英",
            "Name": "",
            "MarginL": "0",
            "MarginR": "0",
            "MarginV": "0",
            "Effect": "",
            "Text": script[i]['content']
        })
    return result

def writeOutAss(path: str, script: list[dict[str, str]]):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(preContext)
        for i in range(len(script)):
            f.write(f'Dialogue: {script[i]["Layer"]},{script[i]["Start"]},{script[i]["End"]},{script[i]["Style"]},{script[i]["Name"]},{script[i]["MarginL"]},{script[i]["MarginR"]},{script[i]["MarginV"]},{script[i]["Effect"]},{script[i]["Text"]}\n')

def batchProcess():
    for root, dirs, files in os.walk('srt'):
        for file in files:
            if file.endswith('.srt'):
                script = readInSrt(os.path.join(root, file))
                script = srtToAss(script)
                writeOutAss(os.path.join('ass', file.replace('.srt', '.ass')), script)

batchProcess()
    